name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - mkdocs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install --requirement requirements.txt
      - run: mkdocs gh-deploy --force