name: Copy branches main to documentation 
env:
  REPO_OWNER: hannesdelbeke

# Controls when the action will run.
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # TODO run janitor on markdown input

  copy-content-to-mkdocs-branch:
    runs-on: ubuntu-latest
    steps:

      - name: checkout source repo
        uses: actions/checkout@v2
        with: 
          path: src_repo
      
      - name: checkout target repo (branch)
        uses: actions/checkout@v2
        with: 
          path: dst_repo
          ref: mkdocs

      - name: remove docs folder
        run: rm --force -r dst_repo/docs

      # load content files in submodule in the docs folder
      - name: load submodule
        uses: actions/checkout@v2
        with: 
          repository: hannesdelbeke/brain
          path: temp_submodule

      # first move image, then notes. mkdir if folder not exists
      - name: move submodule files to dst_repo
        run: |
            mkdir -p dst_repo/static/images/
            mv temp_submodule/image/* dst_repo/static/images/

            rm --force -r temp_submodule/.git
            mkdir -p dst_repo/docs/
            mv temp_submodule/* dst_repo/docs/

      # # push repo
      # - name: push updates to mkdocs branch
      #   # uses: ad-m/github-push-action@master
      #   # with:
      #   #   directory: dst_repo
      #   run: |
      #       cd dst_repo
      #       git config --global user.name github-actions
      #       git config --global user.email github-actions@github.com
      #       git add .
      #       git commit -m "copy notes and images"
      #       git push
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install py requirements
        run: |
            cd dst_repo
            pip install --requirement requirements.txt
      - name: build mkdocs & deploy to github pages
        run: |
            cd dst_repo
            mkdocs gh-deploy --force
